import { Metadata } from "next";
import { GoogleTagManager } from "@next/third-parties/google";

import { ENV } from "@/configs/env";
import { inter } from "@/styles/fonts/fonts";
import { Header } from "@/components/header/header";
import { ROUTES } from "@/types/enums/routes.enums";
import { JsonLd } from "@/components/json-ld/json-ld";
import { ORGANIZATION_SCHEMA } from "@/configs/json-ld";
// import { GoogleTagManager } from "@/components/google-tag-manager/google-tag-manager";

import "./globals.css";

export const metadata: Metadata = {
  title: "Seo tutorial",
  description: "Generated by create next app",
  metadataBase: new URL(ENV.NEXT_PUBLIC_BASE_URL),
  openGraph: {
    title: "Seo tutorial",
    description: "Generated by create next app",
  },
  alternates: {
    canonical: ROUTES.HOME,
  },
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}

        <JsonLd json={ORGANIZATION_SCHEMA} />

        <GoogleTagManager gtmId={ENV.NEXT_PUBLIC_GTM_ID} />

        {/* <GoogleTagManager gtmId={ENV.NEXT_PUBLIC_GTM_ID} /> */}
      </body>
    </html>
  );
}
